# -*- coding: utf-8 -*-
"""
Reusable functions for analytical FCC, VFE, VME statistics.

Equation references
-------------------
* A. Baski, R. Jagatramka, and M. Daly, "A mechanistic model for vacancy
energetics in concentrated solid solutions with short-range order" 
Cohesive/SRO statistics: Eqs. (1)-(9); average VFE/VME:
Eqs. (10)-(11); spreads: Eqs. (12)-(14) and Appendix B.

* ``CMS-2022``: Jagatramka et al., Computational Materials Science 214
(2022) 111763; random-alloy limit of the cohesive statistics, Eqs. (1)-(10).

The perfect-FCC structure factors are generated by
``rdf_coord.rdf_coord_fcc`` and passed in by the workflow; the
vacancy and saddle-point environments are loaded from pre-exported pickle
files in ``data/coordination``.
"""

from __future__ import annotations

import copy
import pickle
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple, Union

import numpy as np
import pandas as pd

import Potential as pot_defect


PathLike = Union[str, Path]


def load_pickle(filename: PathLike) -> Any:
    """Load and return an object stored in a pickle file."""
    with open(filename, "rb") as file_handle:
        return pickle.load(file_handle)

def load_alpha_parameters(
    alpha_file: PathLike | None,
    use_alpha: bool,
    number_of_shells: int,
    number_of_elements: int,
) -> np.ndarray:
    """
    Load Warren-Cowley parameters or create zeros for a random alloy.
    """
    expected_shape = (
        number_of_shells,
        number_of_elements,
        number_of_elements,
    )

    if not use_alpha:
        return np.zeros(expected_shape, dtype=float)

    if alpha_file is None:
        raise ValueError(
            "alpha_file must be supplied when use_alpha=True."
        )

    alpha = np.asarray(np.load(alpha_file), dtype=float)

    if alpha.shape != expected_shape:
        raise ValueError(
            "Alpha shape mismatch: "
            f"expected {expected_shape}, got {alpha.shape}."
        )

    return alpha


def load_coordination_environments(
    pickle_file: PathLike,
    normalization_length: float,
) -> List[np.ndarray]:
    """
    Load and normalize defect coordination environments.

    The first column of each environment is divided by
    ``normalization_length``.
    """
    raw_environments = load_pickle(pickle_file)

    normalized_environments: List[np.ndarray] = []

    for environment in raw_environments:
        normalized = np.asarray(
            copy.deepcopy(environment),
            dtype=float,
        )

        if normalized.ndim != 2:
            raise ValueError(
                f"An environment in {pickle_file} is not two-dimensional."
            )

        normalized[:, 0] /= normalization_length
        normalized_environments.append(normalized)

    return normalized_environments


def get_unique_environments(
    environments: Sequence[np.ndarray],
) -> Tuple[List[np.ndarray], np.ndarray]:
    """Return unique environments and their occurrence frequencies."""
    counts = Counter(
        tuple(map(tuple, np.asarray(environment)))
        for environment in environments
    )

    unique_environments = [
        np.asarray(key, dtype=float)
        for key in counts.keys()
    ]

    frequencies = np.asarray(
        list(counts.values()),
        dtype=int,
    )

    return unique_environments, frequencies


def calculate_fcc_reference(
    potential_file: PathLike,
    composition: np.ndarray,
    lattice_parameter: float,
    cn_fcc: np.ndarray,
    alpha: np.ndarray,
) -> Dict[str, Any]:
    """
    Read the EAM/alloy potential and calculate perfect-FCC statistics.
    """
    rrange, rhorange, rho, Fr, Pp = pot_defect.potential_read(
        str(potential_file)
    )

    cn_perfect = copy.deepcopy(cn_fcc)
    cn_perfect[:, 0] *= lattice_parameter

    coh_fcc, _, element_energy_fcc = pot_defect.potential_stats(
        rrange,
        rhorange,
        rho,
        Fr,
        Pp,
        composition,
        cn_perfect,
        alpha,
    )

    if not np.all(np.isfinite(coh_fcc["E"].to_numpy(dtype=float))):
        raise ValueError(
            "Non-finite FCC reference statistics; check the potential, "
            "lattice parameter, cutoff radius, and alpha inputs."
        )

    return {
        "rrange": rrange,
        "rhorange": rhorange,
        "rho": rho,
        "Fr": Fr,
        "Pp": Pp,
        "coh_fcc": coh_fcc,
        "element_energy_fcc": element_energy_fcc,
        "fcc_mean": float(coh_fcc["E"].iloc[0]),
        "fcc_std": float(coh_fcc["E"].iloc[1]),
    }


def calculate_vfe_statistics(
    unique_environments: Sequence[np.ndarray],
    frequencies: np.ndarray,
    lattice_parameter: float,
    composition: np.ndarray,
    alpha: np.ndarray,
    potential_data: Dict[str, Any],
) -> Dict[str, Any]:
    """Calculate analytical vacancy-formation-energy statistics.

    Mean VFE: vacancy-manuscript Eq. (10). Per-environment excess spread:
    Eq. (12). Aggregation over environments: Eq. (13) and Appendix B, Eq. (B.3)
    """
    number_of_sites = len(unique_environments)
    statistics = np.zeros((number_of_sites, 6), dtype=float)

    coh_fcc = potential_data["coh_fcc"]
    element_energy_fcc = potential_data["element_energy_fcc"]

    mean_vfe = 0.0
    variance_sum_1 = 0.0
    variance_sum_2 = 0.0

    for index, environment in enumerate(unique_environments):
        cn_local = copy.deepcopy(environment)
        cn_local[:, 0] *= lattice_parameter

        coh_site, _, element_energy_vfe = pot_defect.potential_stats(
            potential_data["rrange"],
            potential_data["rhorange"],
            potential_data["rho"],
            potential_data["Fr"],
            potential_data["Pp"],
            composition,
            cn_local,
            alpha,
        )
        
        if not np.all(np.isfinite(coh_site["E"].to_numpy(dtype=float))):
            raise ValueError("Non-finite defect-site energy statistics encountered; check variance/covariance inputs.")

        fcc_mean = float(coh_fcc["E"].iloc[0])
        fcc_std = float(coh_fcc["E"].iloc[1])
        site_mean = float(coh_site["E"].iloc[0])
        site_std = float(coh_site["E"].iloc[1])

        covariance = (
            np.sum(
                composition
                * element_energy_vfe
                * element_energy_fcc
            )
            - site_mean * fcc_mean
        )

        statistics[index, :] = [
            index,
            fcc_mean,
            fcc_std,
            site_mean,
            site_std,
            covariance,
        ]

        frequency = frequencies[index]

        # Population-weighted excess cohesive energy, Eq. (10):
        # E_VFE = sum_k N_k^vac (E_k^vac - E_FCC).
        mean_vfe += (
            site_mean - fcc_mean
        ) * frequency

        # Excess-energy variance, Eq. (12b), using the manuscript
        # near-perfect-correlation approximation cov(E_k,E_FCC) ~=
        # sigma_k*sigma_FCC. The explicitly calculated covariance above is
        # retained in the output table for diagnostics but is not used here.
        sigma_excess = (
            site_std**2
            + fcc_std**2
            - 2.0 * site_std * fcc_std
        )

        # First term of Eq. (B.3a): sum_k N_k sigma_{Delta E_k}^2.
        variance_sum_1 += frequency * sigma_excess

        # Intra-environment covariance term in Eq. (B.3a), assuming all atoms
        # sharing environment k fluctuate coherently (perfect intra-shell
        # correlation, Appendix B).
        variance_sum_2 += (
            2.0
            * sigma_excess
            * frequency
            * (frequency - 1)
            / 2.0
        )

    # Equivalent to Eq. (13): sigma_VFE^2 = sum_k (N_k^vac)^2
    # sigma_{Delta E_k}^2.
    std_vfe = np.sqrt(
        variance_sum_1 + variance_sum_2
    )

    statistics_df = pd.DataFrame(
        statistics,
        columns=[
            "VFE atom site",
            "Efcc average",
            "Efcc stdev",
            "Evfe average",
            "Evfe stdev",
            "covar",
        ],
    )

    std_vfe_check = np.sqrt(
        np.sum(
            frequencies.astype(float) ** 2
            * (
                statistics_df["Efcc stdev"].to_numpy() ** 2
                + statistics_df["Evfe stdev"].to_numpy() ** 2
                - 2.0
                * statistics_df["Evfe stdev"].to_numpy()
                * statistics_df["Efcc stdev"].to_numpy()
            )
        )
    )

    return {
        "mean_vfe": float(mean_vfe),
        "std_vfe": float(std_vfe),
        "std_vfe_check": float(std_vfe_check),
        "site_statistics": statistics_df,
    }


def calculate_ts_vme_statistics(
    unique_environments: Sequence[np.ndarray],
    frequencies: np.ndarray,
    lattice_parameter: float,
    composition: np.ndarray,
    alpha: np.ndarray,
    potential_data: Dict[str, Any],
    mean_vfe: float,
    std_vfe: float,
) -> Dict[str, Any]:
    """
    Calculate transition-state excess-energy and VME statistics.

    Mean VME follows vacancy-manuscript Eq. (11): transition-state excess
    cohesive energy minus the mean VFE. Transition-state spread follows Eqs.
    (12)-(13) applied to the saddle-point environments, and VME spread follows
    Eq. (14).

    """
    number_of_sites = len(unique_environments)
    statistics = np.zeros((number_of_sites, 6), dtype=float)

    coh_fcc = potential_data["coh_fcc"]

    mean_ts = 0.0
    variance_sum_1 = 0.0
    variance_sum_2 = 0.0

    for index, environment in enumerate(unique_environments):
        cn_local = copy.deepcopy(environment)
        cn_local[:, 0] *= lattice_parameter

        coh_site, _, _ = pot_defect.potential_stats(
            potential_data["rrange"],
            potential_data["rhorange"],
            potential_data["rho"],
            potential_data["Fr"],
            potential_data["Pp"],
            composition,
            cn_local,
            alpha,
        )
        
        if not np.all(np.isfinite(coh_site["E"].to_numpy(dtype=float))):
            raise ValueError("Non-finite defect-site energy statistics encountered; check variance/covariance inputs.")

        fcc_mean = float(coh_fcc["E"].iloc[0])
        fcc_std = float(coh_fcc["E"].iloc[1])
        site_mean = float(coh_site["E"].iloc[0])
        site_std = float(coh_site["E"].iloc[1])

        statistics[index, :] = [
            index,
            fcc_mean,
            fcc_std,
            site_mean,
            site_std,
            0.0,
        ]

        frequency = frequencies[index]

        # Transition-state excess cohesive-energy sum in Eq. (11).
        mean_ts += (
            site_mean - fcc_mean
        ) * frequency

        # Excess-energy variance, Eq. (12b), using the manuscript
        # near-perfect-correlation approximation cov(E_k,E_FCC) ~=
        # sigma_k*sigma_FCC. The explicitly calculated covariance above is
        # retained in the output table for diagnostics but is not used here.
        sigma_excess = (
            site_std**2
            + fcc_std**2
            - 2.0 * site_std * fcc_std
        )

        # First term of Eq. (B.3a): sum_k N_k sigma_{Delta E_k}^2.
        variance_sum_1 += frequency * sigma_excess

        # Intra-environment covariance term in Eq. (B.3a), assuming all atoms
        # sharing environment k fluctuate coherently (perfect intra-shell
        # correlation, Appendix B).
        variance_sum_2 += (
            2.0
            * sigma_excess
            * frequency
            * (frequency - 1)
            / 2.0
        )

    std_ts = np.sqrt(
        variance_sum_1 + variance_sum_2
    )

    # Vacancy migration energy, Eq. (11).
    mean_vme = mean_ts - mean_vfe
    # VME standard deviation, Eq. (14); aggregate TS and VFE
    # distributions are treated as statistically independent.
    std_vme = np.sqrt(
        std_ts**2 + std_vfe**2
    )

    statistics_df = pd.DataFrame(
        statistics,
        columns=[
            "TS atom site",
            "Efcc average",
            "Efcc stdev",
            "ETS average",
            "ETS stdev",
            "covar",
        ],
    )

    return {
        "mean_ts": float(mean_ts),
        "std_ts": float(std_ts),
        "mean_vme": float(mean_vme),
        "std_vme": float(std_vme),
        "site_statistics": statistics_df,
    }


def run_vfe_vme_calculation(
    *,
    potential_file: PathLike,
    lattice_parameter: float,
    composition: Sequence[float],
    fcc_coordination: np.ndarray,
    vacancy_environment_file: PathLike,
    transition_state_environment_file: PathLike,
    use_alpha: bool = False,
    alpha_file: PathLike | None = None,
    environment_normalization_length: float = 3.49869654884664,
) -> Dict[str, Any]:
    """
    Run the complete FCC, VFE, and VME analytical calculation.

    The perfect-FCC structure factors are supplied as ``fcc_coordination``
    (dimensionless first column, generated by ``rdf_coord.rdf_coord_fcc`` in the
     workflow). Vacancy and saddle-point environments are loaded from the
    pickle files and rescaled to the requested lattice parameter.
    """
    composition_array = np.asarray(
        composition,
        dtype=float,
    )

    if composition_array.ndim != 1:
        raise ValueError(
            "Composition must be one-dimensional."
        )

    if np.any(composition_array < 0):
        raise ValueError(
            "Composition fractions cannot be negative."
        )

    if not np.isclose(
        composition_array.sum(),
        1.0,
        atol=1.0e-6,
    ):
        raise ValueError(
            "Composition fractions must sum to 1. "
            f"Current sum = {composition_array.sum():.10f}"
        )

    cn_fcc = np.asarray(fcc_coordination, dtype=float)
    if cn_fcc.ndim != 2 or cn_fcc.shape[1] < 2 or not np.all(np.isfinite(cn_fcc)):
        raise ValueError("fcc_coordination must be a finite (n_shells, 2) array.")

    alpha = load_alpha_parameters(
        alpha_file=alpha_file,
        use_alpha=use_alpha,
        number_of_shells=cn_fcc.shape[0],
        number_of_elements=len(composition_array),
    )

    potential_data = calculate_fcc_reference(
        potential_file=potential_file,
        composition=composition_array,
        lattice_parameter=lattice_parameter,
        cn_fcc=cn_fcc,
        alpha=alpha,
    )

    vacancy_environments = (
        load_coordination_environments(
            pickle_file=vacancy_environment_file,
            normalization_length=(
                environment_normalization_length
            ),
        )
    )

    (
        unique_vacancy_environments,
        vacancy_frequencies,
    ) = get_unique_environments(
        vacancy_environments
    )

    vfe_results = calculate_vfe_statistics(
        unique_environments=(
            unique_vacancy_environments
        ),
        frequencies=vacancy_frequencies,
        lattice_parameter=lattice_parameter,
        composition=composition_array,
        alpha=alpha,
        potential_data=potential_data,
    )

    transition_state_environments = (
        load_coordination_environments(
            pickle_file=(
                transition_state_environment_file
            ),
            normalization_length=(
                environment_normalization_length
            ),
        )
    )

    (
        unique_ts_environments,
        ts_frequencies,
    ) = get_unique_environments(
        transition_state_environments
    )

    vme_results = calculate_ts_vme_statistics(
        unique_environments=unique_ts_environments,
        frequencies=ts_frequencies,
        lattice_parameter=lattice_parameter,
        composition=composition_array,
        alpha=alpha,
        potential_data=potential_data,
        mean_vfe=vfe_results["mean_vfe"],
        std_vfe=vfe_results["std_vfe"],
    )

    return {
        "E_FCC": potential_data["fcc_mean"],
        "Sig_FCC": potential_data["fcc_std"],
        "E_VFE": vfe_results["mean_vfe"],
        "Sig_VFE": vfe_results["std_vfe"],
        "Sig_VFE_check": (
            vfe_results["std_vfe_check"]
        ),
        "E_TS": vme_results["mean_ts"],
        "Sig_TS": vme_results["std_ts"],
        "E_VME": vme_results["mean_vme"],
        "Sig_VME": vme_results["std_vme"],
        "FCC_statistics": potential_data["coh_fcc"],
        "VFE_site_statistics": (
            vfe_results["site_statistics"]
        ),
        "TS_site_statistics": (
            vme_results["site_statistics"]
        ),
        "alpha": alpha,
        "fcc_coordination": cn_fcc,
        "cn_VFE_unique": (
            unique_vacancy_environments
        ),
        "cn_VFE_freq": vacancy_frequencies,
        "cn_TS_unique": unique_ts_environments,
        "cn_TS_freq": ts_frequencies,
    }


def print_summary(
    results: Dict[str, Any],
    precision: int = 8,
) -> None:
    """
    Print FCC cohesive energy and defect-energy results.
    """
    print("=" * 52)
    print("ANALYTICAL ENERGY SUMMARY")
    print("=" * 52)

    print(
        f"FCC cohesive energy average = "
        f"{results['E_FCC']:.{precision}f} eV"
    )
    print(
        f"FCC cohesive energy stdev   = "
        f"{results['Sig_FCC']:.{precision}f} eV"
    )

    print("-" * 52)

    print(
        f"VFE average                 = "
        f"{results['E_VFE']:.{precision}f} eV"
    )
    print(
        f"VFE stdev                   = "
        f"{results['Sig_VFE']:.{precision}f} eV"
    )

    print("-" * 52)

    print(
        f"TS excess energy average    = "
        f"{results['E_TS']:.{precision}f} eV"
    )
    print(
        f"TS excess energy stdev      = "
        f"{results['Sig_TS']:.{precision}f} eV"
    )

    print("-" * 52)

    print(
        f"VME average                 = "
        f"{results['E_VME']:.{precision}f} eV"
    )
    print(
        f"VME stdev                   = "
        f"{results['Sig_VME']:.{precision}f} eV"
    )

    print("=" * 52)
